/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report service health and version */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured fantasy leagues */
        get: operations["listLeagues"];
        put?: never;
        /** Create a fantasy league */
        post: operations["createLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/rules/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview league settings and scoring rules recognized from a user-supplied PDF or CSV */
        post: operations["importLeagueRules"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        /** Get one league configuration */
        get: operations["getLeague"];
        /** Replace a league configuration */
        put: operations["updateLeague"];
        post?: never;
        /** Delete a league and its draft history */
        delete: operations["deleteLeague"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Duplicate a league configuration without its draft history */
        post: operations["duplicateLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/mock-drafts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a disposable mock draft using a league's current rules */
        post: operations["createMockDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a versioned league backup as a new league */
        post: operations["importLeagueBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        /** Download a versioned league configuration backup */
        get: operations["exportLeagueBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/exports/rankings.csv": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        /** Download league-weighted consensus rankings as CSV */
        get: operations["exportConsensusRankingsCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/exports/draft.csv": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        /** Download current draft results as CSV */
        get: operations["exportDraftResultsCSV"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueId}/exports/draft.json": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        /** Download versioned draft results as JSON */
        get: operations["exportDraftResultsJSON"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in ranking feeds and their refresh status */
        get: operations["listRankingSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-sources/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download and normalize every built-in ranking feed */
        post: operations["refreshRankingSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-sources/{sourceId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Download and normalize one built-in ranking feed */
        post: operations["refreshRankingSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-sources/import-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect and import a supported user-supplied ranking PDF */
        post: operations["importRankingPDF"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-sources/import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a private ordinal ranking source from CSV */
        post: operations["importRankingCSV"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projection-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user-imported granular projection sources */
        get: operations["listProjectionSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projection-sources/import-csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import granular player projections from CSV */
        post: operations["importProjectionCSV"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List potentially ambiguous canonical player matches */
        get: operations["listRankingIdentityIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/player-directory/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarize persisted canonical player identities */
        get: operations["getPlayerDirectoryStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-identities/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a human review of an identity issue */
        post: operations["reviewRankingIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build a league-weighted consensus from every imported feed */
        get: operations["getConsensusRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking-watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find players favored by sources excluded from the league consensus */
        get: operations["getRankingWatchlist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current draft board and recommendations */
        get: operations["getDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft a player to my team or mark the player taken */
        post: operations["recordDraftAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the current league season's draft */
        post: operations["startDraftSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/session/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear current-season selections while preserving league assets */
        post: operations["resetDraftSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/session/undo-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore the selections removed by the most recent reset */
        post: operations["undoDraftSessionReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade eligible draft assets between two teams */
        post: operations["createDraftTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/trades/{tradeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Reverse a trade whose assets remain eligible */
        delete: operations["deleteDraftTrade"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/trades/{tradeId}/condition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Resolve a pending conditional future pick */
        put: operations["resolveDraftTradeCondition"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close the current dynasty season and start the next draft */
        post: operations["advanceDraftSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo the most recent active draft action */
        post: operations["undoDraftAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a player as a target, avoid, or neutral */
        put: operations["setDraftPlayerPreference"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate opponent picks until the user's next turn */
        post: operations["simulateDraftToNextTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/sync/sleeper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import current picks from a public Sleeper draft */
        post: operations["syncSleeperDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Health: {
            /** @constant */
            status: "ok";
            /** @example draftmeld */
            service: string;
            /** @example 0.3.0 */
            version: string;
        };
        LeagueRules: {
            name: string;
            teamCount: number;
            /** @description Zero means the league has not assigned the user's draft position yet. */
            draftPosition: number;
            userTeamNumber: number;
            teamNames: string[];
            draftOrder: number[];
            /** @enum {string} */
            draftType: "snake" | "linear" | "auction";
            /** @enum {string} */
            leagueFormat: "redraft" | "dynasty";
            season: number;
            initialSeason: number;
            futurePickSeasons: number;
            rookieDraftRounds: number;
            auctionBudgetTrades: boolean;
            faabBudget: number;
            faabTrades: boolean;
            rosterSlots: components["schemas"]["RosterSlot"][];
            /** @description Custom points per projected event. Missing or zero-valued categories are disabled. */
            scoringRules: {
                [key: string]: number;
            };
            /** @description Per-source inclusion and influence. Missing source IDs use enabled published defaults. */
            sourcePreferences: {
                [key: string]: components["schemas"]["RankingSourcePreference"];
            };
            /** @enum {string} */
            consensusMethod: "weighted-average" | "weighted-median" | "trimmed-mean";
            playerPreferences: {
                [key: string]: "target" | "avoid";
            };
            auctionBudget: number;
            auctionMinimumBid: number;
            keeperBudgetSpent: number;
            myKeeperSpend: number;
            keeperValueRemoved: number;
        };
        League: {
            id: string;
        } & components["schemas"]["LeagueRules"];
        LeagueRuleImport: {
            /** @enum {string} */
            fileType: "pdf" | "csv";
            rules: {
                [key: string]: number;
            };
            matches: components["schemas"]["LeagueRuleMatch"][];
            settings: components["schemas"]["ImportedLeagueSettings"];
            settingMatches: components["schemas"]["LeagueSettingMatch"][];
            warnings: string[];
        };
        LeagueRuleMatch: {
            key: string;
            label: string;
            value: number;
            source: string;
            /** @enum {string} */
            confidence: "high" | "medium";
        };
        LeagueSettingMatch: {
            key: string;
            label: string;
            value: string;
            source: string;
            /** @enum {string} */
            confidence: "high" | "medium";
        };
        ImportedRosterSlot: {
            name: string;
            count: number;
            positions: string[];
            isStarting: boolean;
        };
        ImportedLeagueSettings: {
            name?: string;
            teamCount?: number;
            /** @enum {string} */
            draftType?: "snake" | "linear" | "auction";
            /** @enum {string} */
            leagueFormat?: "redraft" | "dynasty";
            futurePickSeasons?: number;
            rookieDraftRounds?: number;
            auctionBudget?: number;
            auctionMinimumBid?: number;
            auctionBudgetTrades?: boolean;
            faabBudget?: number;
            faabTrades?: boolean;
            rosterSlots?: components["schemas"]["ImportedRosterSlot"][];
        };
        LeagueBackup: {
            /** @constant */
            formatVersion: 1;
            /** Format: date-time */
            exportedAt: string;
            originalLeagueId: string;
            rules: components["schemas"]["LeagueRules"];
            recommendationPolicy: components["schemas"]["RecommendationPolicy"];
        };
        RecommendationPolicy: {
            baseScore: number;
            startingNeedBonus: number;
            adpValueThreshold: number;
            scarcityBonus: number;
            scarcityDropOff: number;
            recommendationLimit: number;
        };
        RosterSlot: {
            name: string;
            count: number;
            positions: string[];
            isStarting: boolean;
        };
        RankingSource: {
            id: string;
            name: string;
            description: string;
            methodology: string;
            license: string;
            projectUrl: string;
            dataUrl: string;
            defaultWeight: number;
            /** @enum {string} */
            importMode: "download" | "pdf-upload" | "csv-upload";
            /** @enum {string} */
            role: "ranking" | "market" | "usage";
            isCustom: boolean;
            recordCount: number;
            /** Format: date-time */
            refreshedAt?: string | null;
            publishedAt?: string;
        };
        RankingSourcePreference: {
            weight: number;
            enabled: boolean;
        };
        RankingPDFImport: {
            source: components["schemas"]["RankingSource"];
            pageCount: number;
            /** @description True when the PDF had no selectable text and local OCR was used. */
            ocrApplied: boolean;
        };
        ConsensusRanking: {
            playerKey: string;
            name: string;
            /** @enum {string} */
            position: "QB" | "RB" | "WR" | "TE" | "K" | "DST";
            team: string;
            rank: number;
            score: number;
            sourceCount: number;
            sourceRanks: {
                [key: string]: number;
            };
            coverage: number;
            rankRange: number;
            /** @enum {string} */
            confidence: "high" | "medium" | "low";
            /** @enum {string} */
            method: "weighted-average" | "weighted-median" | "trimmed-mean";
            adp: number;
            tier: number;
        };
        ProjectionSource: {
            id: string;
            name: string;
            recordCount: number;
            /** Format: date-time */
            importedAt: string;
        };
        IdentityCandidate: {
            playerKey: string;
            name: string;
            position: string;
            team: string;
        };
        PlayerDirectoryStatus: {
            playerCount: number;
            identityCount: number;
            providerIdCount: number;
        };
        IdentityIssue: {
            issueKey: string;
            reason: string;
            candidates: components["schemas"]["IdentityCandidate"][];
            /** @enum {string} */
            resolution: "confirmed-separate" | "acknowledged" | "merged" | "";
            canonicalPlayerKey?: string;
        };
        WatchlistSignal: {
            sourceId: string;
            sourceName: string;
            sourceRank: number;
            spotsHigher: number;
        };
        WatchlistPlayer: {
            playerKey: string;
            name: string;
            /** @enum {string} */
            position: "QB" | "RB" | "WR" | "TE" | "K" | "DST";
            team: string;
            consensusRank: number | null;
            signals: components["schemas"]["WatchlistSignal"][];
        };
        Player: {
            id: string;
            name: string;
            nflTeam: string;
            /** @enum {string} */
            position: "QB" | "RB" | "WR" | "TE" | "K" | "DST";
            byeWeek: number;
            overallRank: number;
            positionRank: number;
            adp: number;
            tier: number;
            projectedPoints: number;
            valueOverReplacement: number;
            confidence: string;
            rankRange: number;
            /** @enum {string} */
            preference: "target" | "avoid" | "";
            auctionValue: number;
        };
        Recommendation: {
            player: components["schemas"]["Player"];
            score: number;
            reasons: string[];
        };
        Pick: {
            eventId: number;
            number: number;
            /** @enum {string} */
            action: "draft" | "taken";
            player: components["schemas"]["Player"];
            /** Format: date-time */
            createdAt: string;
            cost: number;
            teamNumber: number;
            teamName: string;
        };
        DraftTeam: {
            number: number;
            name: string;
            isUser: boolean;
            roster: components["schemas"]["Player"][];
            auctionBudgetRemaining: number;
        };
        DraftSnapshot: {
            leagueId: string;
            leagueName: string;
            pickNumber: number;
            available: components["schemas"]["Player"][];
            myTeam: components["schemas"]["Player"][];
            teams: components["schemas"]["DraftTeam"][];
            history: components["schemas"]["Pick"][];
            recommendations: components["schemas"]["Recommendation"][];
            canUndo: boolean;
            dataMode: string;
            projectionCount: number;
            /** @enum {string} */
            draftType: "snake" | "linear" | "auction";
            nextUserPick: number;
            auctionBudget: number;
            budgetRemaining: number;
            auctionInflation: number;
            auctionMinimumBid: number;
            maximumBid: number;
            isUserTurn: boolean;
            totalPicks: number;
            isComplete: boolean;
            onClockTeamNumber: number;
            pickSlots: components["schemas"]["DraftPickSlot"][];
            pickTrades: components["schemas"]["DraftPickTrade"][];
            /** @enum {string} */
            leagueFormat: "redraft" | "dynasty";
            season: number;
            auctionBudgetTrades: boolean;
            faabTrades: boolean;
            budgetBalances: components["schemas"]["BudgetBalance"][];
            draftOrder: number[];
            /** @description Zero means the position has not been assigned yet. */
            draftPosition: number;
            userTeamNumber: number;
            /** @enum {string} */
            sessionStatus: "not-started" | "in-progress" | "complete";
            canReset: boolean;
            canUndoReset: boolean;
        };
        MockDraftSession: {
            id: string;
            leagueId: string;
            name: string;
        };
        MockDraftRequest: {
            draftPosition?: number;
        };
        DraftPickSlot: {
            season: number;
            overallNumber: number;
            round: number;
            pickInRound: number;
            originalTeamNumber: number;
            originalTeamName: string;
            ownerTeamNumber: number;
            ownerTeamName: string;
            isUsed: boolean;
        };
        DraftPickTrade: {
            id: number;
            leagueId: string;
            teamOneNumber: number;
            teamOneName: string;
            teamTwoNumber: number;
            teamTwoName: string;
            teamOneReceives: number[];
            teamTwoReceives: number[];
            teamOneFuturePicks: components["schemas"]["FutureDraftPick"][];
            teamTwoFuturePicks: components["schemas"]["FutureDraftPick"][];
            teamOneAuctionBudget: number;
            teamTwoAuctionBudget: number;
            teamOnePlayers: string[];
            teamTwoPlayers: string[];
            teamOneBudgets: components["schemas"]["BudgetAsset"][];
            teamTwoBudgets: components["schemas"]["BudgetAsset"][];
            season: number;
            /** Format: date-time */
            createdAt: string;
        };
        FutureDraftPick: {
            season: number;
            round: number;
            originalTeamNumber: number;
            originalTeamName: string;
            condition: string;
            /** @enum {string} */
            conditionStatus: "" | "pending" | "met" | "not-met";
        };
        FutureDraftPickRequest: {
            season: number;
            round: number;
            originalTeamNumber: number;
            condition?: string;
        };
        DraftPickTradeRequest: {
            leagueId: string;
            teamOneNumber: number;
            teamTwoNumber: number;
            teamOneReceives: number[];
            teamTwoReceives: number[];
            teamOneFuturePicks: components["schemas"]["FutureDraftPickRequest"][];
            teamTwoFuturePicks: components["schemas"]["FutureDraftPickRequest"][];
            teamOneAuctionBudget: number;
            teamTwoAuctionBudget: number;
            teamOnePlayers: string[];
            teamTwoPlayers: string[];
            teamOneBudgets: components["schemas"]["BudgetAsset"][];
            teamTwoBudgets: components["schemas"]["BudgetAsset"][];
        };
        BudgetAsset: {
            /** @enum {string} */
            kind: "auction" | "faab";
            season: number;
            amount: number;
        };
        BudgetBalance: {
            teamNumber: number;
            season: number;
            /** @enum {string} */
            kind: "auction" | "faab";
            remaining: number;
        };
        TradeConditionRequest: {
            leagueId: string;
            season: number;
            round: number;
            originalTeamNumber: number;
            /** @enum {string} */
            status: "met" | "not-met";
        };
        SeasonRolloverRequest: {
            leagueId: string;
            season: number;
            /** @enum {string} */
            draftType: "snake" | "linear" | "auction";
            draftOrder: number[];
        };
        DraftExport: {
            /** @constant */
            formatVersion: 1;
            /** Format: date-time */
            exportedAt: string;
            leagueId: string;
            leagueName: string;
            /** @enum {string} */
            draftType: "snake" | "linear" | "auction";
            picks: components["schemas"]["Pick"][];
            myTeam: components["schemas"]["Player"][];
        };
        SleeperSyncResult: {
            snapshot: components["schemas"]["DraftSnapshot"];
            added: number;
            updated: number;
            removed: number;
            unmatched: number;
        };
        DraftActionRequest: {
            leagueId: string;
            playerId: string;
            /** @enum {string} */
            action: "draft" | "taken";
            cost?: number;
            teamNumber?: number;
        };
        DraftSessionRequest: {
            leagueId: string;
        };
        DraftStartRequest: {
            leagueId: string;
            /** @description The user's selected position for this real draft. */
            draftPosition?: number;
        };
        DraftResetRequest: {
            leagueId: string;
            confirmation: string;
        };
    };
    responses: {
        /** @description The request was not valid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request conflicts with the current draft state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request could not be completed. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        LeagueId: string;
        LeagueIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DraftMeld is ready to accept requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listLeagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured leagues ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueRules"];
            };
        };
        responses: {
            /** @description League created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    importLeagueRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Recognized rules for user review. The uploaded file is not retained. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueRuleImport"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The uploaded file exceeds the 20 MiB limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The file was readable but contained no supported league settings or scoring rules. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueRules"];
            };
        };
        responses: {
            /** @description Updated league configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    duplicateLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description League duplicated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createMockDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockDraftRequest"];
            };
        };
        responses: {
            /** @description Mock draft created and started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockDraftSession"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    importLeagueBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueBackup"];
            };
        };
        responses: {
            /** @description Backup restored as a new league without overwriting the original. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["League"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The backup exceeds the 256 KiB limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exportLeagueBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portable league backup. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueBackup"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportConsensusRankingsCSV: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consensus rankings with source evidence and weights. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportDraftResultsCSV: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active draft picks in pick order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    exportDraftResultsJSON: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                leagueId: components["parameters"]["LeagueIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versioned draft result export. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftExport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRankingSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking source catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSource"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    refreshRankingSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed ranking sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSource"][];
                };
            };
            /** @description An upstream ranking feed could not be downloaded or parsed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshRankingSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed ranking source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSource"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description The upstream ranking feed could not be downloaded or parsed. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    importRankingPDF: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The detected ranking source was normalized and imported. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingPDFImport"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The uploaded PDF exceeds the 20 MiB limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    importRankingCSV: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    /** Format: binary */
                    file: string;
                    /** @description JSON object mapping DraftMeld field names to source CSV headers. */
                    mapping?: string;
                };
            };
        };
        responses: {
            /** @description The private ranking source was normalized and imported. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSource"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listProjectionSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Imported projection sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionSource"][];
                };
            };
        };
    };
    importProjectionCSV: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    /** Format: binary */
                    file: string;
                    /** @description JSON object mapping DraftMeld field names to source CSV headers. */
                    mapping?: string;
                };
            };
        };
        responses: {
            /** @description Imported projection source. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionSource"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listRankingIdentityIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reviewable identity issues. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityIssue"][];
                };
            };
        };
    };
    getPlayerDirectoryStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical player directory counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDirectoryStatus"];
                };
            };
        };
    };
    reviewRankingIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    issueKey: string;
                    /** @enum {string} */
                    resolution: "confirmed-separate" | "acknowledged" | "merged";
                    canonicalPlayerKey?: string;
                };
            };
        };
        responses: {
            /** @description Identity review saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConsensusRankings: {
        parameters: {
            query: {
                leagueId: components["parameters"]["LeagueId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized consensus rankings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsensusRanking"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getRankingWatchlist: {
        parameters: {
            query: {
                leagueId: components["parameters"]["LeagueId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to five meaningful disabled-source ranking outliers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistPlayer"][];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    getDraft: {
        parameters: {
            query: {
                leagueId: components["parameters"]["LeagueId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    recordDraftAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftActionRequest"];
            };
        };
        responses: {
            /** @description Updated draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Player is no longer available. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startDraftSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftStartRequest"];
            };
        };
        responses: {
            /** @description Started draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["ServerError"];
        };
    };
    resetDraftSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftResetRequest"];
            };
        };
        responses: {
            /** @description Reset draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    undoDraftSessionReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSessionRequest"];
            };
        };
        responses: {
            /** @description Restored draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["ServerError"];
        };
    };
    createDraftTrade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftPickTradeRequest"];
            };
        };
        responses: {
            /** @description Draft state with the updated pick ownership schedule. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDraftTrade: {
        parameters: {
            query: {
                leagueId: components["parameters"]["LeagueId"];
            };
            header?: never;
            path: {
                tradeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft state with the trade reversed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    resolveDraftTradeCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tradeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeConditionRequest"];
            };
        };
        responses: {
            /** @description Draft state with the condition resolved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    advanceDraftSeason: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeasonRolloverRequest"];
            };
        };
        responses: {
            /** @description Fresh next-season draft state with persistent dynasty assets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    undoDraftAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    leagueId: string;
                };
            };
        };
        responses: {
            /** @description Updated draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description There is no active action to undo. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    setDraftPlayerPreference: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    leagueId: string;
                    playerId: string;
                    /** @enum {string} */
                    preference: "target" | "avoid" | "";
                };
            };
        };
        responses: {
            /** @description Updated draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
        };
    };
    simulateDraftToNextTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    leagueId: string;
                };
            };
        };
        responses: {
            /** @description Draft state after simulated opponent picks. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
        };
    };
    syncSleeperDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    leagueId: string;
                    sleeperDraftId: string;
                    rosterId: number;
                };
            };
        };
        responses: {
            /** @description Reconciliation summary and draft state after Sleeper synchronization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SleeperSyncResult"];
                };
            };
        };
    };
}
