/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report service health and version */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current draft board and recommendations */
        get: operations["getDraft"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft a player to my team or mark the player taken */
        post: operations["recordDraftAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draft/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo the most recent active draft action */
        post: operations["undoDraftAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        Health: {
            /** @constant */
            status: "ok";
            /** @example draftmeld */
            service: string;
            /** @example 0.2.0 */
            version: string;
        };
        LeagueRules: {
            name: string;
            teamCount: number;
            /** @enum {string} */
            draftType: "snake" | "linear" | "auction";
            rosterSlots: components["schemas"]["RosterSlot"][];
            scoringRules: {
                [key: string]: number;
            };
        };
        RosterSlot: {
            name: string;
            count: number;
            positions: string[];
            isStarting: boolean;
        };
        Player: {
            id: string;
            name: string;
            nflTeam: string;
            /** @enum {string} */
            position: "QB" | "RB" | "WR" | "TE";
            byeWeek: number;
            overallRank: number;
            positionRank: number;
            adp: number;
            tier: number;
        };
        Recommendation: {
            player: components["schemas"]["Player"];
            score: number;
            reasons: string[];
        };
        Pick: {
            eventId: number;
            number: number;
            /** @enum {string} */
            action: "draft" | "taken";
            player: components["schemas"]["Player"];
            /** Format: date-time */
            createdAt: string;
        };
        DraftSnapshot: {
            leagueId: string;
            leagueName: string;
            pickNumber: number;
            available: components["schemas"]["Player"][];
            myTeam: components["schemas"]["Player"][];
            history: components["schemas"]["Pick"][];
            recommendations: components["schemas"]["Recommendation"][];
            canUndo: boolean;
        };
        DraftActionRequest: {
            leagueId: string;
            playerId: string;
            /** @enum {string} */
            action: "draft" | "taken";
        };
    };
    responses: {
        /** @description The request was not valid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request could not be completed. */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        LeagueId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DraftMeld is ready to accept requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getDraft: {
        parameters: {
            query: {
                leagueId: components["parameters"]["LeagueId"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    recordDraftAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftActionRequest"];
            };
        };
        responses: {
            /** @description Updated draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Player is no longer available. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    undoDraftAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    leagueId: string;
                };
            };
        };
        responses: {
            /** @description Updated draft state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSnapshot"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description There is no active action to undo. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
